elasticsearch:
  host: localhost # default: please don't change this if not necessary
  port: 9200 # default: please don't change this if not necessary
  index_name: defects4j # NECESSARY: change this to your index name.
#  index_name: bench4bl # For Bench4BL dataset
#  index_name: bench4bl_full_100 # For Bench4BL dataset
#  index_name: bench4bl_fixed # For Bench4BL dataset
#  index_name: bench4blsum # For Bench4BL dataset
#  index_name: bench4blaj # For Bench4BL dataset

Fields:
  project: keyword
  sub_project: keyword
  version: keyword
  source_code: text
  file_url: keyword
#  bug_id: keyword
#  bug_summary: text
#  bug_description: text
